### ISSUE TITLE
V1 endpoints return pre V1 keyset ids

### ISSUE THREAD

**Issue by thesimplekid** [cashubtc/nutshell#512]
curl -X GET https://8333.space:3338/v1/keys                                                                      
```
{"keysets":[{"id":"I2yN+iRYfkzT","unit":"sat","keys":{"1":"03ba786a2c0745f8c30e490288acd7a72dd53d65afd292ddefa326a4a3fa14c566","2":"03361cd8bd1329fea797a6add1cf1990ffcf2270ceb9fc81eeee0e8e9c1bd0cdf5","4":"036e37..
```

Version is `Nutshell/0.15.2` is returning pre v1 keyset ids in both the `/v1/keys` and `/v1/keysets` according to the spec all keysets should be the new hex format and this breaks desensitization if that is enforced. Non v1 keysets should only be accepted and returned on the pre v1 endpoints.

**Comment by callebtc** [comment]
Thank you for this issue. I know this is dirty :( 

The reason nutshell does this is because it has already given out ecash with old keysets to clients. Clients that update to v1 need to be able to keep using it. I am working on a PR that will allow us to rotate away from these old keysets for existing mints (and for all and not old keysets in a new deployment anymore). I hope that will work out for you, if not let me know!

**Comment by thesimplekid** [comment]
> The reason nutshell does this is because it has already given out ecash with old keysets to clients. 

Aren't the `/keys` and `/keysets` endpoints still active and those could be used for interacting with the old ids and keep the `/v1/*` only new keysets?

>  I am working on a PR that will allow us to rotate away from these old keysets for existing mints (and for all and not old keysets in a new deployment anymore). I hope that will work out for you, if not let me know!

Yeah that's okay I already handle it on the `/v1/keysets` endpoint I'll do the same on the `/v1/keys` and can look back at it later.

**Comment by callebtc** [comment]
> Aren't the `/keys` and `/keysets` endpoints still active and those could be used for interacting with the old ids and keep the `/v1/*` only new keysets?
> 
> >

That is a good point, however it would require that the wallet can interact with both protocols at the same time. I've decided to go this route so that wallets that implement for example cashu-ts v1 only have to talk the v1 protocol and can still spend their old ecash. Eventually, hopefully, when all existing mints rotated away from old keysets ID's these tokes shouldnt' be around at some point anymore. 

I hope....

**Comment by callebtc** [comment]
Closing as non-issue.
